---
- name: Install Nginx
  apt:
    name: "{{ nginx_packages }}"
    default_release: "{{ nginx_packages_release | default(omit) }}"
    state: present
  notify:
    - Restart Nginx

- name: Create configuration file
  template:
    src: "{{ nginx_config_template }}"
    dest: "{{ nginx_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload Nginx

- name: Configure Nginx service
  service:
    name: "{{ nginx_service }}"
    enabled: "{{ nginx_enable }}"

- name: Set Nginx service state
  service:
    name: "{{ nginx_service }}"
    state: "{{ nginx_state }}"
  register: _nginx_service_state
