---
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint .
verifier:
  name: ansible
platforms:
  - name: ${MOLECULE_INSTANCE_NAME:-ansible-role-nginx-instance}
    image: ansible-role-nginx:debian-10
    dockerfile: Dockerfile.j2
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/sbin/init"
    privileged: true
    tty: true
dependency:
  name: shell
  command: molecule/link-mitogen.sh
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
